#!/usr/bin/env node
// 產線腳本(P1-5):node build.js 一鍵由 data/venues.json + config/family.json + template.html 產出 dist/
// dist 僅含公開頁面與 PWA 資產;config/ 與 data/ 不會被部署
const fs = require('fs');
const path = require('path');
const R = __dirname;
const DIST = path.join(R, 'dist');
const TODAY = new Date().toISOString().slice(0, 10);

const venues = JSON.parse(fs.readFileSync(path.join(R, 'data/venues.json'), 'utf8'));
const fam = JSON.parse(fs.readFileSync(path.join(R, 'config/family.json'), 'utf8'));

// 頁面層資料(fee 尚非 schema 欄位,結構化待 schema v2)
const FEE_SHORT = {
  "luodong-sports-park": "免門票・停車 30–50 元/次",
  "dongshan-river-eco-ark": "門票 30 元(未滿 6 歲/未滿 115cm 免)・停車 50 元",
  "yilan-sports-park": "免費入園",
  "longtan-lake-scenic-area": "免門票・停車 50 元/次",
  "wuyuan-water-fire-park": "全免費・24 小時開放",
  "shuilu-kids-cafe": "門票 300 元可折 200(100–120cm 半票 200)",
  "lanyang-estuary-kids-restaurant": "低消每人一餐/飲(100cm 以下免低消)",
  "gitu-cafe-manor": "低消每人一杯飲料或一份餐點・停車免費",
  "lao-si-g-tea-coffee": "低消每人 100 元・可餵魚",
  "amaze-rabbit-maze-jiaoxi-bath": "門票 350 元可全折(6 歲以下 50 元不可折)",
  "lucky-art-crayon-castle": "250 元含 4 項 DIY(可折部分消費)",
  "anyo-museum": "250 元可全折(未滿 3 歲免)",
  "wooderful-life-luodong": "免費參觀・木作 DIY 另計",
  "hsus-legend-vinegar-factory": "免門票・兩層樓溜滑梯免費",
  "lanyang-museum": "常設展 100 元(未滿 6 歲/未滿 115cm 免)",
  "dongshanriver-water-park": "平時免門票(童玩節 7/4–8/16 需門票,未滿 6 歲免)",
  "wulaokeng-scenic-area": "全票 80 元・停車 50 元(綠博期間另計)",
  "suao-cold-spring-park": "泡腳與公園免費・大眾池 120/60 元",
  "yi-nong-ranch": "150 元(5 歲以下免)含羊奶+飼料",
  "bambi-land": "200 元含飼料(0–5 歲免)",
  "grandma-zhang-mei-farm": "200 元含餵食(2–4 歲 50 元)",
  "jimmy-square": "免費・24 小時開放",
  "luodong-cultural-working-house": "免門票・停車 30 元/時",
  "ncfta-yilan": "150 元(未滿 6 歲/115cm 以下免)・縣民 100",
  "meihua-lake": "免費入園・停車約 100 元/次",
  "chung-hsing-cultural-park": "免費入園・停車 30 元/時",
  "luodong-likoyung-library": "免費入館(休館日多,出發前確認)",
  "yilan-art-museum": "50 元(未滿 6 歲/縣民免)",
  "wanglongpi": "免門票・停車免費",
  "taipei-zoo": "100 元(未滿 6 歲免)・市民 60",
  "taipei-childrens-amusement-park": "入園 30 元(6 歲以下免)・設施 20–30 元/項",
  "ntsec": "常設展 120 元(未滿 6 歲或 115cm 以下免)",
  "taipei-astronomical-museum": "展示館 40 元(學齡前免)",
  "daan-forest-park": "免費・24 小時開放",
  "juzhixiang": "免門票・DIY 150 元起",
  "xihe-sandaime": "100 元可全折(120cm 以下免)",
  "yutu-pencil-school": "200 元含 DIY(3 歲以下免)・預約制",
  "jiaoxi-tangweigou": "泡腳免費・大眾湯 80 元",
  "paoma-historic-trail-park": "免費・光雕秀免費",
  "jianiao-garden": "100 元可全折(100cm 以下免)",
  "xingbao-scallion-farm": "拔蔥+蔥派 DIY 約 220 元・預約制",
  "guangxing-farm": "入園 100/200 可折・控窯 800 起・預約制",
  "yilanbing-museum": "免門票・牛舌餅 DIY 180 元",
  "sabelina": "250 元含印畫 DIY(3 歲以下免)",
  "luwu-japanese-garden": "300 元可折 100(未滿 6 歲/115cm 以下免)",
  "shengyang-water-plant-farm": "100 元可全折(100cm 以下免)",
  "herbelle": "100 元可全折(115cm 以下免)",
  "keda-goat-farm": "50 元可全折(100cm 以下免)・銅板價",
  "huaquan-organic-farm": "100 元可全折(100cm 以下免)・預約制",
  "atters-cake": "免門票・DIY 團體預約",
  "imit-rice": "免門票・冷泉泡腳免費",
  "kingcar-aquaculture": "200 元不可折・餵鯊魚 300/次",
  "toucheng-leisure-farm": "約 600 元(含餐/導覽/DIY)・預約制",
  "junbaobei": "免費入館・DIY 另計",
  "annong-river-park": "免費・24 小時開放",
  "luodong-forestry-culture-park": "免費入園・停車 60 元/時",
  "baimi-clogs": "250 元含 DIY 抵用券・預約制",
  "tiger-rice-noodle": "200 元含 DIY+米粉吃到飽(3 歲以下免)",
  "brick-museum-yilan": "約 200–250 元含 3 項 DIY",
  "doctor-duck": "100 元可全折・DIY 需預約",
  "happiness-farm-20": "100 元可全折(100cm 以下免)",
  "lanyang-creative": "免費入園・餐飲/DIY 另計",
  "changpi-lake": "免費・24 小時開放(付費樂園區另計)",
  "dongyue-spring": "免費・季節限定 6–10 月開放",
  "tiansongpi-station": "免費入園・五分仔小火車 50 元",
  "shilin-residence": "庭園免費・正館 100 元(學齡前免)",
  "ntm-taipei": "30 元(未滿 6 歲免)・四館聯票 130",
  "beitou-hotspring-museum": "免費",
  "taipei-water-park": "水鄉庭園 80 元(6 歲以下免)・親水樂園另購",
  "huashan-1914": "免費入園・展覽另購",
  "rongxing-garden": "免費・24 小時(整建中)",
  "maokong-gondola": "單程 180 元(未滿 6 歲免)・一日票 300",
  "tfam-kids": "兒藝中心免費・主館 30 元",
  "youth-park-taipei": "免費・游泳池另收",
  "dahu-park": "免費・24 小時開放",
  "tc-nmns-science-museum": "展示場門票 100 元(未滿 6 歲免費)・停車半小時 15 元",
  "tc-nmns-botanical-garden": "溫室門票 20 元(未滿 6 歲免費)",
  "tc-beitun-childrens-park": "免費",
  "tc-carton-king-dakeng": "入園 200 元(含園區折抵券・100cm 以下免費・18:00 後免費入園)",
  "tc-island-aurora": "低消:大人約 400-480 元、兒童(80-140cm)250-280 元、80cm 以下免費",
  "tc-qiuhonggu-park": "免費入園・地下停車收費(費率待確認)",
  "tc-shoes-wonderland": "門票100元(4-7歲/長者50元、3歲以下免費),可全額折抵消費",
  "tc-national-taichung-theater": "公共區免費・表演與特展另購票・停車收費",
  "tc-tongyou-forest": "1大1小3小時330元(假日360)/全日499元(假日599)・餐點另計無低消",
  "tc-civic-park": "免費入園・地下停車收費",
  "tc-rainbow-village": "免費入場・停車約 30 元/時",
  "tc-fengle-sculpture-park": "免費・停車另計",
  "tc-ntmofa-children": "免費(互動體驗空間需線上預約)",
  "tc-caowu-greenway": "免費・停車另計",
  "tc-taichung-park": "免費入園・停車半小時15元(划船每船300元/時)",
  "tc-4th-credit-union": "免費入場・冰淇淋一球約90元起",
  "tc-cultural-heritage-park": "免費入園・停車半小時20元起",
  "tc-showtime-station-front": "入場免費・遊樂區/影城另計",
  "tc-nlpi-library": "免費入館・停車每30分10元",
  "tc-lihpao-land": "探索/馬拉灣分開售票(門票以官網為準)・3歲以下未滿100cm免費・停車約40元/時",
  "tc-lihpao-outlet": "商場免費入場・停車40元/時(消費可折抵)・摩天輪電子票約150元(現場一般票約250元)",
  "tc-houli-horse-farm": "入園門票以官網為準・停車100元/次・餵馬/騎馬體驗另計",
  "tc-zhongshe-flower": "賞花門票以現場為準(烤肉吃到飽者免門票)・停車免費",
  "tc-waipu-wangyou-valley": "免費・田邊路旁停車",
  "tc-xinshe-castle": "門票350元(7-12歲250)・停車50",
  "tc-lavender-forest": "門票200元(12歲以下免費)・可折抵100",
  "tc-dongshi-forest": "門票250元(幼童125)・停車50",
  "tc-muxinquan-farm": "門票200元(6歲以下免費)・免費停車",
  "tc-baigu-manor": "免費入園・親子DIY 250元起(6歲以下免費)",
  "tc-gaomei-wetland": "免費入場・停車約50元",
  "tc-aofeng-gulu-park": "免費・停車免費",
  "tc-mitsui-outlet-port": "免費入場・ASOBI 平日150/假日200元(30分)",
  "tc-wuqi-fishing-port": "免費入場・停車50元",
  "tc-qingshui-ghost-cave": "免費(入洞需登記)",
  "tn-linmoniang-park": "免費・停車另計",
  "tn-anping-tree-house": "門票70元(半票35,台南市民憑證免費)",
  "tn-eternal-golden-castle": "門票70元(半票35,台南市民免費)・停車30元",
  "tn-anping-saltoffice": "免門票(生日鹽/彩鹽蛋/水豚互動等另購)",
  "tn-anping-childrens-museum": "兒童票平日35/50、假日70/100元;家長60元",
  "tn-hele-plaza": "免費・停車另計",
  "tn-confucius-temple": "外圍免費・大成殿門票25元",
  "tn-chihkan-tower": "門票70元(台南市民免費)",
  "tn-art-museum-2": "全票160元(16歲以下兒童免費)",
  "tn-fire-museum": "免費",
  "tn-barclay-park": "免費入園・停車另計",
  "tn-ncku-campus": "免費",
  "tn-austin-land-nanfang": "1大1小約539元起(3小時)",
  "tn-tainan-park": "免費入園(天鵝船另計)",
  "tn-shueijiaoshe": "戶外免費・場館銅板價門票",
  "tn-taijiang-visitor-center": "免費・周邊停車免費",
  "tn-sicao-green-tunnel": "船票 全票200元・6歲以下30元",
  "tn-nmth": "門票 100元(6歲以下免)・停車 50元/次",
  "tn-yantian-eco-village": "免費(園區開放)",
  "tn-luermen-shengmu-temple": "免費(漢服體驗 100元起)",
  "tn-nanke-archaeology": "門票80元(未滿6歲免)",
  "tn-tree-valley-science": "門票80元(未滿6歲免)",
  "tn-shanhua-beer": "免費入場・免費停車",
  "tn-tree-valley-farm": "門票80元(含餵食紅蘿蔔一杯,未滿6歲收費待確認)",
  "tn-shanshang-waterworks": "博物館區門票100元(未滿6歲免);淨水池區免費",
  "tn-wanpi-world": "門票 全票平日499/假日550元(3歲以下免費)・停車80元",
  "tn-jianshanpi": "門票 全票150元(3歲以下免費)・三合一套票約250元",
  "tn-nanyuan-farm": "門票 全票350元(未滿4歲免費)・停車50元",
  "tn-zoumalai-farm": "門票 幼童/博愛120元(3歲以下免費)・停車轎車50元(全票金額待確認)",
  "tn-cowhome": "門票 80元(可折抵30元・90cm以下免費)・停車免費",
  "tn-cigu-saltmountain": "免費入園・停車100元",
  "tn-jingzaijiao-saltfield": "免費・停車免費",
  "tn-beimen-crystalchurch": "免費入園(教堂內部依現場公告)",
  "tn-cigu-visitorcenter": "免費入場"
};
const FEE_FULL = {
  "luodong-sports-park": "免門票;附設停車場收費時間08:00–21:00,小客車平日30元/次、假日50元/次(官方收費辦法);17:00後僅設籍宜蘭縣民眾憑國民身分證免費停車,部落格所稱「每次計3小時、17時後免費」以現場公告為準",
  "dongshan-river-eco-ark": "門票每人30元(單一費率,2017/7/1起實施)。免費:設籍宜蘭縣民、身高未滿115cm或未滿6歲兒童、身障者及陪同1人;17:00-22:00免費入園(部分園區不開放)。停車另計:小客車50元/機車20元/大客車100元(身障停車證免費)。園內神秘河道電動小船:日航每人75元(滿3歲-未滿12歲半票35元、未滿3歲免費)、包船8人600元、夜航包船約1200元;水上自行車為第三方付費行程。注意勿與冬山車站橋下『冬山舊河道電動小船』(100/50)混淆。",
  "yilan-sports-park": "免費入園(戶外公園,部落格明稱「無料景點」);園內室內游泳池、國民運動中心等場館使用另行收費(收費標準見宜蘭國民運動中心官網 yilansports.com.tw,金額待確認)。",
  "longtan-lake-scenic-area": "免門票;停車小客車50元/次、大客車100元/次(18:00–次日08:00免費;悠活園區停車可消費折抵)。註:2025年委外台塑生醫經營後規劃湖畔餐廳/市集,收費制度變動風險低但建議定期複查",
  "wuyuan-water-fire-park": "免費(免門票、免費停車、24小時開放)",
  "shuilu-kids-cafe": "全票 NT$300(120cm以上,可折抵館內消費200元);半票 NT$200(100-120cm,部分來源載 65 歲以上與身障亦適用,可折抵100元);身高 100cm 以下免費(另有近期來源寫 110cm 以下免票,標準略有出入、以現場為準)。每張門票含飼料兌換券及踩踩飛車(小火車)體驗一次;免費停車場。以上票價於本次對抗查證由多來源交叉再確認。",
  "lanyang-estuary-kids-restaurant": "無門票。低消:每人一份餐點或飲品,100 公分以下免低消(多來源含政府平台一致);主餐(義大利麵/燉飯/日式咖哩等)約 NT$300 上下(部落格 2025 菜單,價格可能異動);任兩份主餐+NT$400 可升級套餐(麵包x2+主廚濃湯x2+任選飲品x2+甜點蜂蜜吐司/鬆餅擇一,約每人+200);均消約 NT$360-600 為部落格推估;不收服務費;僅收現金(無刷卡)。",
  "gitu-cafe-manor": "免門票/無入園費;低消每人一杯飲料或一份餐點(單點約 NT$100-380);禁帶外食與寵物。停車免費。(fonfood 與 tinalife 2026-07-19 重查一致)",
  "lao-si-g-tea-coffee": "免門票(餐廳型態);每人低消 NT$100(2025-03 部落格資訊);用餐後店家提供魚飼料可餵魚(原稱『自由打賞』之打賞機制待確認);有部落格稱僅收現金(現況待確認)。",
  "amaze-rabbit-maze-jiaoxi-bath": "門票350元(13歲以上)、250元(7-12歲),皆可全額折抵消費;6歲以下(學齡前)50元保險清潔費,不可折抵。室內限時約120分鐘(每組2小時,含參觀與用餐),戶外不限時。免費停車。(2026-07-19 經 kafu.tw 2026 文與多來源複驗一致)",
  "lucky-art-crayon-castle": "全票250元(含4項DIY,可折抵館內消費;折抵金額各來源記載80–100元不等,以現場為準);宜蘭縣民票235元、愛心票125元;未滿3歲及65歲以上免門票陪同入場(無DIY);彩虹溜滑梯另計:單次體驗150元、持門票加購100元(限滿6歲、體重未滿100kg)",
  "anyo-museum": "全票250元(官網公告,2026-07-01起生效),可全額折抵館內消費(DIY/用餐/伴手禮,射擊體驗除外);未滿3歲、70歲以上、身障者+陪同1人免費;宜蘭縣民平日免費。暑期加碼:憑2026童玩節票根免費入館(至8/31)。註:部落格舊資料載全票200元屬改版前票價,以官網250元為準;滑步車租借另約200-300元、收涎抓周方案優惠價1500元(原價1800)。",
  "wooderful-life-luodong": "免門票免費參觀、免預約(僅羅東門市免費,其他分店收費);付費項目:木作DIY(音樂盒、相框等,依品項計價,每日16:30截止)與商品販售;停車另計(周邊付費停車場1小時60元、平日上限100元)",
  "hsus-legend-vinegar-factory": "免門票、免低消入館;兩層樓旋轉溜滑梯免費無限次(約2~12歲、限重約50kg);三層樓白金溜滑梯需滿8歲或身高130cm以上,憑館內消費發票/捐發票玩——換算規則各來源不一(每30元一次/滿100元一張玩一次/一張300元發票玩10次),以現場公告為準,發票捐宜蘭在地社福團體;醋醋小火車、旋轉木馬、娛樂機台為投幣付費;DIY 體驗(優酪乳手工皂等)另收費(價格待確認);停車免費。",
  "lanyang-museum": "常設展全票 NT$100,身高未滿 115 公分或未滿 6 歲免費(須一位購票大人陪同);官方售票 FAQ 另列全票 NT$200(推測為含特展票種,細項待確認);兒童考古探索廳另購票 NT$50/場(45 分鐘,現場抽號);停車另計(委外收費停車場,機車免費)。",
  "dongshanriver-water-park": "平時免門票,僅收停車費(小客車50/機車20/大客車100);電動小船需另付費(票價據TravelKing為單程全票75/優待票35,2026-07-19未能再確認,以現場公告為準);童玩節期間(2026/7/4-8/16)需門票:個人券假日350/平日250、兒童券假日200/平日100,未滿6歲或身高未滿115公分免費",
  "wulaokeng-scenic-area": "非綠博期間:全票80/優待票60(30人以上團體、軍警公教學生)/半票40(110cm以上兒童、65歲以上),宜蘭縣民憑證及身障免費;另有部落格(桃桃's)載全票100,以現場公告為準。停車小客車50/機車20/大客車100。綠博期間門票另計(2026年平日全票150、假日250,縣民100)",
  "suao-cold-spring-park": "泡腳區與公園免費;大眾池全票120元/半票60元(3-12歲、65歲以上;「130cm以下半票」為舊制70/40元時代標準,已過時),蘇澳鎮民平日免費假日半票;傳統湯屋單人300元/多人每人200元,冷熱雙泉(VIP)湯屋雙人約850元、頂級湯屋(含烤箱)雙人約1200元;公有停車場08:00-17:00收費(機車20元/小型車50元/大型車100元/次),其餘時段免費;以現場公告為準",
  "yi-nong-ranch": "全票150元(13-65歲)、半票100元(6-12歲、66歲以上、身障者),5歲(含)以下免費;門票含鮮羊奶(或飲料)+牧草飼料;停車免費",
  "bambi-land": "全票200元(含一份飼料);優待票50元(6-12歲、65歲以上、身障者及必要陪同1名);0-5歲免費;飼料餵完可加購,禁止自帶食物餵食",
  "grandma-zhang-mei-farm": "5歲以上200元(含入園+餵食草料1份;部分來源稱另含甜點飲品,內含物各來源不一需現場確認);2-4歲清潔費50元;65歲以上或身心障礙150元;DIY體驗套票350元(含門票+草料+食農DIY+田園拔菜,需預約);浴衣租借大人100元、120cm以下小孩50元",
  "jimmy-square": "幾米廣場免費、24小時開放;幸福轉運站戶外區過往免費,官方旅遊網現列夏令(5-10月)週四至週二9:30-18:00、冬令9:00-17:30、週三休館,惟營運現況有矛盾證據、以電洽為準;室內收費現況待確認(幾米團隊時期僅球池收費約100-150元,2021年後易主);周邊停車每小時20-50元(後站停車場最近、假日易滿)",
  "luodong-cultural-working-house": "免門票免費參觀(特殊展覽視主辦單位是否售票);附設停車場每小時30元(10分鐘內免費,平日上限150元、假日上限180元)",
  "ncfta-yilan": "全票150元、優惠票120元(6歲以上學生)、宜蘭縣民100元、敬老票75元、未滿6歲或115公分以下免費;年卡350元(縣民年卡250元、敬老年卡100元);停車前30分鐘免費、每小時30元、當日上限60元;DIY另計(如手機架DIY 200元、月河遊船3-12歲100元、未滿3歲免費)",
  "meihua-lake": "免費入園。停車費記載不一:2026 年來源載計次收費一次100元(較新);較早親子部落格載每小時50元、租車可折抵,以現場公告為準。遊湖船全票75元/半票35元;人力協力車約200-300元、四輪電輔車約300-500元/輛",
  "chung-hsing-cultural-park": "免費入園(戶外與展館皆免門票);停車費小客車30元/時(週一至四上限90元、週五至日及國定假日上限150元)、大客車60元/時、機車20元/次、自行車免費;手作DIY課程與部分特展依各工坊/活動公告另計(興工一場染布體驗約250-350元,其餘價格待確認)",
  "luodong-likoyung-library": "免費入館(玩全台灣旅遊網景點頁與文化部博物之島館舍資料均載明免費)",
  "yilan-art-museum": "全票50元;身高未滿115公分或未滿6歲兒童免費、設籍宜蘭縣縣民免費;優待票30元(團體30人以上);持蘭陽博物館常設展票根優惠30元(檢索 2026-07-19,依官網購票資訊頁)",
  "wanglongpi": "免門票、停車免費;周邊自費項目:花田村湖畔咖啡簡餐、窯烤披薩DIY約250元起、魚飼料(2024 年資訊,價格待重驗);另有望龍埤鵝肉攤低消20元麵食",
  "taipei-zoo": "全票100元、優待票50元、臺北市民票60元、團體票70元;未滿6歲免費(2024-04-01調漲後現行價,CNA與官網雙源證實);遊園列車每趟5元(學齡前免費,悠遊卡或投幣);娃娃車租借每次50元(押證件或押金1000元);園外停車場另計費",
  "taipei-childrens-amusement-park": "入園全票30元、7-12歲優待票15元、6歲以下免費;大型設施15項(編號1-13+K1/K2)每項20-30元,一日樂Fun券200元暢玩編號1-13(星光票140元,16:00後),小型委外設施50-80元;2026暑期水樂園300元、水陸聯票480元;停車平日30元/時、假日40元/時",
  "ntsec": "常設展(3–6F)全票120元、學生/一般團體90元(2026-01-01起,凍漲16年後首次調漲);未滿6歲或身高115公分以下兒童、65歲以上免費(修正:原稿僅載115公分以下)。兒童益智探索館另購票全票60元、2歲以下免費、每場限售220張(2025年報導稱兒童館收費不在此波調漲內,實際票價建議現場確認);空中腳踏車、3D劇場另計;地下停車場收費",
  "taipei-astronomical-museum": "展示館全票40元、臺北市民20元(可刷悠遊卡);宇宙劇場100元、宇宙探險70元;學齡前兒童、在校學生免費入展示館;1樓特展免費",
  "daan-forest-park": "免費入園;附設地下停車場計時收費(假日白天約 40 元/時、平日白天約 20 元/時、夜間 10 元/時,半小時計費)",
  "juzhixiang": "入園免門票、免費停車、販賣部外免費熱金棗茶;DIY另計:金棗/金橘蜜餞DIY約150-200元/份(ETtoday實測150元/約20分)、金桔(季節限定)果醬DIY約900元/3罐、香桔酥DIY約700元/6片;玻璃屋咖啡館餐點/飲品多在100元上下。價格以現場/官網為準。",
  "xihe-sandaime": "普通票100元(可全額折抵館內消費/體驗,含50元抵用券+50元體驗券);優待票50元(65歲以上、身心障礙者及陪同1位);120公分以下兒童免費入館。DIY另計,如小魚飯糰小卷約150元。免費停車。",
  "yutu-pencil-school": "2026一般票200元（含導覽+鉛筆DIY），半票/敬老/身障100元，3歲以下免費；不參加活動、僅逛福利社（販售區）免門票。票價已由先前150元調漲為200元",
  "jiaoxi-tangweigou": "戶外泡腳池免費;湯圍風呂(大眾湯)全票80元、優待票60元(軍公教/身障/110cm以上學生)、半票40元(65歲以上);溫泉魚SPA約成人70-80元、兒童(4歲~國小六年級)60元、部分攤商未滿4歲免費。90cm以下兒童禁入湯屋。",
  "paoma-historic-trail-park": "免費：免門票、免停車費；夜間『山光脈動』光雕秀亦免費（curly.com.tw、walkerland.com.tw、宜蘭勁好玩官網）。",
  "jianiao-garden": "門票每人100元,可全額折抵消費(飼料/DIY/餐飲,折抵不找零);100公分以下由家長陪同免費入場。親子DIY約160–380元。",
  "xingbao-scallion-farm": "付費預約制(2026 各通路價,以官網/現場為準):蔥田導覽+拔蔥+蔥派DIY+伴手禮券 約220元/人;純動物互動(迷你驢/梅花鹿,含牧草+50元抵用券)約200-220元/人;三星蔥+動物雙體驗套票 約380元/人;未滿7歲免入園費,2-4歲現場清潔費50元(可折抵、無專屬體驗材料)",
  "guangxing-farm": "入園門票:3-12歲$100(可折抵$50)、12歲以上$200(可折抵$150),票券可折抵場內消費並合併使用;摸蜆體驗$200/人(限3歲以上);焢窯每窯約$800-900(含場地、指導、柴火、食材;多數來源列$800-900,少數列$750起,以現場梯次為準);彩繪陶瓷小豬撲滿$180/人、發光燈泡生態瓶$200/缸;餵食飼料$10/包;附免費停車場。查證 2026-07-19,焢窯價格已依多數來源修正為$800-900範圍。",
  "yilanbing-museum": "入館免門票、免費停車;牛舌餅DIY每人180元(2026現行值,舊資料150元;可帶回6片超薄宜蘭餅、體驗約60-80分鐘,4歲以下可由一位家長陪同);2樓3D彩繪館憑館內消費發票免費參觀,僅週六、日開放。",
  "sabelina": "全票NT$250(一般遊客,含印畫DIY素材抵用券與商品/紀念品抵用券,商品可折抵150元或換紀念品);愛心票NT$100(65歲以上及身心障礙者,含DIY抵用券);3歲以下免票(不含DIY體驗)。導覽採預約制(場次約10:00、14:00),停車免費。",
  "luwu-japanese-garden": "門票(2026官網):全票300、學生票270、優惠票250、愛心票150;未滿6歲或身高未滿115公分免費入園;門票可折抵館內消費100元",
  "shengyang-water-plant-farm": "入園門票100元/人,可全額折抵園區消費(100元分為兩張50元抵用卷,限釣蝦/水草商店/水草咖啡廳等指定消費,部分商品除外);100公分以下幼兒免費入園;生態瓶等DIY體驗與水草餐廳消費另計。",
  "herbelle": "入園清潔維護費100元/人,可全額折抵園內消費(DIY/餐飲/商品);身高115cm以下孩童免費入場。花園自助午餐成人NT$450+10%、兒童NT$280+10%(可折抵100元);投幣賽車約50元/次;多肉/香皂/精油等DIY可用門票折抵。",
  "keda-goat-farm": "入園門票每人50元、可全額折抵園內消費;身高100公分以下幼童免費。動物食物每份約20-50元(牧草餵大羊約30元/把、紅蘿蔔或羊奶餵兔/小羊50元/份、飼料餵雞鴨鵝20元/包);另有『動物快樂餵食餐』約130-180元(可餵多種動物並兌換羊奶鬆餅/冰淇淋/咖啡等);擠羊奶體驗約200元/次;陶瓷娃娃彩繪、羊奶饅頭/披薩/冰淇淋DIY等為另計付費活動。整體屬銅板價。(2026-07-19 WebSearch 復核:牧草30元/把、紅蘿蔔50元/份、飼料20元/包、擠羊奶200元、130元套餐等數字一致。)",
  "huaquan-organic-farm": "場地清潔維護費100元/人(可全額折抵園區消費),身高100公分以下兒童免費入園;另有花泉一日遊套餐約750元/人(含園區導覽、香草乳液DIY、田媽媽風味午餐、水中生態觀察、小小水族箱DIY等)。",
  "atters-cake": "免門票免費入館、免費停車;免費招待氣泡水/黑咖啡/蜂蜜涼茶及多款蛋糕試吃;DIY另計(手工餅乾180元/人、手工蛋黃酥250元/人,需20人以上團體、平日開班、假日不開班且須提前預約繳訂金)",
  "imit-rice": "入館免門票、免費停車、免費試吃與紅豆水暢飲;DIY需付材料費——官網雪莓娘DIY材料費2入180元/3入250元,操作約20–30分,建議6歲以下一大一小,場次10:00/11:00/14:00/15:00;造型麻糬等其他DIY金額以現場或電洽03-9907779#500為準。",
  "kingcar-aquaculture": "門票:全票200元、優待票(3~11歲)150元、100公分以下/愛心票(65歲以上/孕婦/身心障礙及一名陪同者)100元;門票一律不可折抵消費(WebSearch 多數來源一致為『100公分以下仍需100元』,惟少數頁面誤記為免費,以收費為準)。加購體驗:餵鯊魚300元/次、水母餵食100元/次、花園鰻餵食100元/次。停車免費。",
  "toucheng-leisure-farm": "入園門票約$600/人(2026-07-19 WebSearch 多來源複查一致);孩童3歲以下免費入園、3-10歲購孩童票(現場購買)、11歲以上同大人;平日參加『一日遊體驗之旅』成人約9折;生態半日體驗優惠約TWD 900(含入園門票、DIY、自助傳統小吃);詳細套裝價格以官網/電話最新公告為準。",
  "junbaobei": "入館參觀免費;DIY體驗需付費(如金柑乾洗手凝露、水嫩乳液、驅黑面膜、晚安凍膜、北蟲草接菌、優格等,另有四人DIY套票於KKday/Taipei Fun Pass販售,實際價格依現場/官網方案);停車免費。確切DIY單價未於檢索結果取得,標『待確認』",
  "annong-river-park": "免費(免門票、免費停車場)",
  "luodong-forestry-culture-park": "免費入園;停車另收費(小型車每小時60元,平日當日最高100元)",
  "baimi-clogs": "現行官方售票頁(baimiclogs.boostime.me,2025-2026):全票250元、優惠票200元(宜蘭縣民/65歲以上憑證),身心障礙者、身高115cm以下、蘇澳鎮鎮民免費;門票含館內導覽與200元DIY抵用券(工藝DIY體驗)。採預約制。註:2026-07-19 WebSearch 查證發現票價存在來源矛盾——部分旅遊網/舊版資料仍列全票150/優惠100(舊制,免費含3歲以下),2022年前部落格另記免門票、DIY約100-150元;以官方預約售票頁現行250元含抵用券為準,實際以預約當下官網公告為主,建議行前致電03-9952653確認",
  "tiger-rice-noodle": "全票200元(含一張DIY兌換券+100元抵用券);優惠票100元(65歲以上、12歲以下、宜蘭縣籍、身心障礙者及一名陪同者);3歲以下免費入館。門票含古早味炒米粉免費吃到飽,電鍋炒米粉/彩繪碗DIY以門票兌換券折抵;另有手作米粉DIY需加收工本費;免費停車。WebSearch 2026-07-19 多來源一致。",
  "brick-museum-yilan": "全票原價 250 元(重新開幕/開幕優惠約 200–230 元;部分來源列平日 220/假日 250)、愛心票約 125–150 元(來源不一,funtime 與樂色山資料多列 125);未滿 3 歲或未滿 90cm 之幼兒及 75 歲以上長者免費;門票含 3 項積木 DIY 與一份(約 20 元)飲料兌換/折抵。實際票價以官網/官方 FB 最新公告為準(來源數字略有出入)。",
  "doctor-duck": "入館全票100元(原價120,3歲以下及身障免費),可全額折抵館內消費;DIY另計並多需3天前預約:彩繪鴨180、古早味鹹鴨蛋180、鴨賞便利包/鴨賞DIY約220-280、櫻桃鴨御飯糰180等",
  "happiness-farm-20": "入園門票100元/人(可全額折抵園內低消),100公分以下幼兒免費;空中樹梢體驗200元起;DIY 180元起",
  "lanyang-creative": "免費入園(免門票);園內餐飲、選品購物、DIY手作體驗等另行付費。",
  "changpi-lake": "長埤湖風景區本體免門票、免費停車、24小時開放(2026 三星鄉公所官網及多篇部落格確認)。園內付費樂園區(原精靈村/現水行俠主題樂園)於2025改版後費用有變動:食尚玩家報導樂園區約50元入園賞湖景步道;動物區/精靈村全票約200元(可折抵消費,部分方案附100元兌換券)、半票約100元(65歲以上及國小生)、幼稚園以下免費;水上活動與和服體驗另計。樂園區營業時間各來源約 9:30–17:30(部分標 9:30–16:10)不一。實際票價與時間以官網 sanshingyolo.com 為準,標『待確認以官網最新公告』。",
  "dongyue-spring": "免門票(免費);對面停車場免費停車。僅需自負交通費,園內有美食文創市集攤販另計",
  "tiansongpi-station": "入園免費;五分仔小火車票$50(身高110cm以下兒童免費、6歲以下需大人陪同);園區消費滿額贈小火車票一張(2025–2026 多數部落格為消費/點餐滿$100送一張,另有滿$200一說,以官方價目表現場公告為準);伐木星空低/高空體驗約$350(7關卡一次$350)–$500(KKday高空方案約$500含小火車票+拍貼)。",
  "shilin-residence": "戶外庭園公園免費入園;僅『正館』室內導覽收門票:全票100元、團體票80元、優待票50元,學齡前兒童與身心障礙者及陪伴者一名免費。停車須另付費(福林公園60元/小時、台灣聯通士林官邸等鄰近收費停車場)",
  "ntm-taipei": "全票30元、半票15元;未滿6歲學齡前兒童免費;65歲以上平日免費、假日半票;四館聯票全票130元/半票65元。本館與古生物館(土銀展示館)可一票或聯票參觀",
  "beitou-hotspring-museum": "免費(門票與定時導覽皆免費)",
  "taipei-water-park": "自來水園區(含水鄉庭園戲水區):夏季(7-8月)全票80/優待40元、非夏季(5、6、9月)全票50/優待25元,6歲以下與65歲以上免費;玩水期間2026/7/4~8/30。注意:園區內2026新開的『親水樂園』(9米雙螺旋滑水道、漂漂河)與水鄉庭園分開售票、門票不共用,暑假平日全票160/假日180、學生票平日130/假日160、3歲以上未滿6歲幼童平日80/假日90(7/4開幕日均一價100元)。置物櫃投幣(小格20/中格30元)、吹風機投幣10元;水岸停車場平日30/假日50元每小時。",
  "huashan-1914": "園區入場免費;特定大型/沉浸式展覽與IP快閃店另行售票(依各展於KKTIX或官網購票)。停車收費(交通部觀光署頁面/園區公告):機車每小時25元、汽車平日每小時40元(單日上限約280元)、假日每小時60元(單日上限約540元);部分部落格另載每半小時25元、單日上限250元等舊資訊,兩者有出入,實際以現場公告為準",
  "rongxing-garden": "免費(24小時開放公園);園區地下停車場另計:小型車約40元/時(半小時計)、機車約10元/時、當日上限約20元(來源:parks/janice.life)",
  "maokong-gondola": "單程單次:全票NT$180/優待NT$50;一日票:全票NT$300/優待NT$100;水晶車廂『貓纜之眼』每趟次每人加NT$50;官方售票資訊:0~5歲(未滿6歲)幼童由購票成人陪同免費(每位成人限帶2名),6~12歲兒童適用優待票NT$50。WebSearch 複驗票價與免費年齡與官方一致",
  "tfam-kids": "兒藝中心(B1)本身免票入場(多篇2025-2026部落格與新聞標示『免門票/免費親子景點』);進入主館常設/特展需全票NT$30、台北市民及6-12歲兒童/學生15,未滿6歲、65歲以上、身障者及必要陪伴者1人免費,週六17:00後停止售票、免費參觀;館方停車場平日NT$30/時、假日40/時。註:各來源對『兒藝中心是否需併購主館票』略有出入(官網票價頁列全票制,部分親子部落格稱免費),實際以現場公告為準",
  "youth-park-taipei": "公園/飛行探索遊戲場/交通公園教學區:免費;萬華親子館:免費(時段制,每場限 80 對)。游泳池另收費(2026 夏季全票 120 元、僅戶外泳池+戲水池 60 元、身心障礙持證免費、公益時段 08:00–10:00 提供 65 歲以上與 55 歲以上原住民持證免費)。停車另計:地下停車場小型車 30 元/半小時、機車 20 元/次(停車費率為部落格轉述,建議現場再確認)",
  "dahu-park": "免費入園、全天開放。開車可停大湖公園地下停車場(計時收費,實際費率待確認);園內另設臺北市立大湖公園游泳池為使用者付費之獨立設施,非本公園免費範圍。",
  "tc-nmns-science-museum": "展示場全票 100 元、優待票(學生)70 元,未滿 6 歲及 65 歲以上免費;太空/立體劇場另購票;停車小型車 15 元/半小時、上限 180 元",
  "tc-nmns-botanical-garden": "植物園溫室全票 20 元、優待票 10 元(6 歲以上未滿 12 歲、65 歲以上假日、20 人以上學生團體),未滿 6 歲免費;綜合服務中心提供娃娃車、輪椅、吹風機借用與寄物",
  "tc-beitun-childrens-park": "公園免費入園;園內/園旁設臺中市立圖書館興安分館與室內遊戲室,可就地作為下雨避雨去處",
  "tc-carton-king-dakeng": "入園門票全票 200 元/人、優待票 100 元(65 歲以上、身障),100 公分以下兒童免費;門票含園區折抵券(各來源稱 50 元或 3 張共 150 元,以現場為準,紙小火車須現金不可折抵);平日 09:00-19:00、假日 09:00-21:00,18:00 後免門票入園",
  "tc-island-aurora": "採低消制:大人約 NT$400-480/人、兒童(80-140 公分)NT$250-280、80 公分以下免費;用餐即可不限時暢玩二樓遊戲區,建議提前預約(平假日常客滿)",
  "tc-qiuhonggu-park": "公園24小時免費開放;停車須付費,汽車約每30分計費、機車採次計費,實際費率以現場為準",
  "tc-shoes-wonderland": "全票100元、優待票50元(4至7歲兒童及65歲以上)、3歲以下免費;門票可全額折抵館內消費,DIY另計",
  "tc-national-taichung-theater": "建築公共區域免費參觀,空中花園開放時段內免費(閉館前15分鐘關閉);表演與特展需另購票,停車須付費",
  "tc-tongyou-forest": "1大1小3小時330元(假日360元)、全日票499元(假日599元),加1名大人+100元(可折30元餐飲);6個月-1歲100元、6個月以下隨大寶免費;門票不折抵,餐點(鬆餅/炸物60元起)另計無低消",
  "tc-civic-park": "草皮公園免費開放;下方市政公園地下停車場24小時收費停車,鄰近七期有百貨與歌劇院可作臨時室內避雨",
  "tc-rainbow-village": "免費入場;開放週二至週日 09:00–17:00(週一休館);旁側停車場收費約 30 元/時",
  "tc-fengle-sculpture-park": "公園免費、24 小時開放;鄰近豐樂停車場(停104/停100)另收停車費",
  "tc-ntmofa-children": "免票入館;臺灣兒童藝術基地互動體驗空間每日 3 場次(09:30-11:00/13:00-14:30/15:00-16:30、各 90 分)需預約,參觀前 14 日開放;開放時間週二至五 09:00–17:00、週六日至 18:00、週一休館",
  "tc-caowu-greenway": "綠園道與兒童公園免費;周邊停車場與路邊停車格另收費;沿線勤美誠品綠園道為室內避暑避雨去處",
  "tc-taichung-park": "入園免費、24小時開放;地下停車場半小時15元、非假日一日上限120元;湖心亭划船一艘300元/小時(限乘3人)",
  "tc-4th-credit-union": "入場免費;冰淇淋單球約90元、綜合冰品/鬆餅百元起(部分高價冰品達450元),另售伴手禮",
  "tc-cultural-heritage-park": "入園與多數展覽免費(部分特展另計);園區開放6:00-22:00、展館9:00-17:00;合作街停車小型車平日半小時20元、假日25元",
  "tc-showtime-station-front": "商場入場免費;湯姆熊採代幣、樂米樂園入場費另計、秀泰影城電影票另購;地下停車消費可折抵",
  "tc-nlpi-library": "入館及兒童學習中心免費(12歲以下兒童及家長);開放週二至週六9:00-20:00、週日9:00-17:00,週一及公告放假日休館;地下停車汽車每30分10元、機車每次10元",
  "tc-lihpao-land": "探索世界與馬拉灣分開售票,票價以官網為準;3歲以下(未滿100cm)幼童由家長陪同免費入園;停車汽車約40元/時,園區消費可折抵",
  "tc-lihpao-outlet": "商場免費入場;天空之夢摩天輪一般車廂票約150元;室內樂園/木育森林另計;停車汽車40元/時,消費滿500折抵1小時、單日上限200元",
  "tc-houli-horse-farm": "全票150元、優待100元(65歲以上/16歲以下持證/團體/軍警),3歲以下及設籍后里、豐原居民免票;停車100元/次;約週四至週二09:30-17:00(週三公休);2026特展為『精靈綠光嘉年華』馬術特技秀,場次/加購以官網公告為準",
  "tc-zhongshe-flower": "停車免費;花海門票依季節約全票120-150元、半票60-75元(以現場公告為準);烤肉吃到飽含門票約成人280-380元、身高100-140cm約170-240元(隨季節浮動),用餐限約2.5小時",
  "tc-waipu-wangyou-valley": "免費開放的稻田景觀,無門票;田邊寬路可暫停車、勿踩踏農作;最佳觀賞為每年7月中前與11月中前的金黃稻浪",
  "tc-xinshe-castle": "全票350、半票250(7-12歲/65歲以上)、博愛175元,門票可折抵100元餐飲(春節不可用);停車清潔費50元/輛",
  "tc-lavender-forest": "入園門票200元,含市值200元以上入園禮並可折抵100元消費;12歲以下兒童、身障者及一名陪同、新社中和里居民免費入園",
  "tc-dongshi-forest": "全票250、學生200、幼童/敬老125元,停車50元;園區含體能訓練場、天空森の道、濯足園泡腳池、露營烤肉區",
  "tc-muxinquan-farm": "全票200(抵100)、半票100(6-12歲/身障,抵50)、6歲以下與80歲以上免費;附免費停車場,設景觀餐廳(火鍋/排餐)",
  "tc-baigu-manor": "入園參觀免費(採購/餐飲/DIY另計);假日親子生態DIY體驗6歲以上250元、6歲以下免費(含採菇/餵雞撿蛋/茶碗蒸/下午茶);泡菜DIY每人200元;附免費停車",
  "tc-gaomei-wetland": "濕地與木棧道免費參觀;小客車停車每次約50元(遊客中心或周邊停車場)",
  "tc-aofeng-gulu-park": "公園與谷溜遊戲場免費;停車免費(自由車場/路邊),假日車位緊張",
  "tc-mitsui-outlet-port": "商場入場與停車免費;ASOBI SQUARE室內樂園平日150、假日200元(30分,陪同票100),一日券450元(限平日);台中之星摩天輪平日成人150/兒童100、假日成人200/兒童150",
  "tc-wuqi-fishing-port": "漁港與漁寮公園免費;觀光漁港停車清潔費50元/次,漁寮公園旁附免費停車場;戲水區3–11月開放(平日14:00-17:10、六日11:00-17:10,每半小時供水10分);海鮮購買或代客料理另計",
  "tc-qingshui-ghost-cave": "免門票,入洞前需於警衛室登記;開放週六日及例假日9:00-16:00,週二至五需10天前團體電話預約,週一及過年不開放",
  "tn-linmoniang-park": "公園免費入場;入口收費停車場另計",
  "tn-anping-tree-house": "全票70/半票35元,一票暢遊樹屋+英商德記洋行+朱玖瑩故居;台南市民憑身分證免費",
  "tn-eternal-golden-castle": "全票70/半票35元,台南市民憑證免費;門口停車場一次30元不限時",
  "tn-anping-saltoffice": "免門票入場;366生日彩鹽、彩鹽蛋、雪鹽燒霜淇淋、水豚互動、漢服體驗等自費",
  "tn-anping-childrens-museum": "平日台南市民童票35/外縣市50;假日台南市民童票70/外縣市100;家長票一律60元;週二至週日9:00-17:00,週一及國定假日休館(部分時段中午休館待確認)",
  "tn-hele-plaza": "免費入場戲水;開放9:00–21:30、週二休;7歲以下須家長陪同,現場無救生員,停車費另計",
  "tn-confucius-temple": "外圍園區免費(8:30–17:30);大成門內收費區每人25元、30人以上團體20元/人",
  "tn-chihkan-tower": "全票70元、半票35元;台南市民出示證件免費;開放時間約8:30–21:30(建議查官方最新公告)",
  "tn-art-museum-2": "全票160元(一/二館通用),團體120元、特別票80元(台南市民/大專生/65歲以上敬老假日);16歲以下兒童及高中生免費,65歲以上平日免費",
  "tn-fire-museum": "免門票參觀;開放時間 09:00–18:00、週一休;15人以上團體導覽須一週前預約,個人免預約",
  "tn-barclay-park": "公園免費開放;停車場/路邊停車依費率另計",
  "tn-ncku-campus": "校園開放免費入園;停車視周邊費率另計",
  "tn-austin-land-nanfang": "一般入場3小時:1-12歲500元、成人150元;線上套票(KKday/klook)1大1小約539元起,價格以官方為準",
  "tn-tainan-park": "公園免費開放;燕潭天鵝船與停車依現場費率另計",
  "tn-shueijiaoshe": "戶外園區免費;飛行親子館銅板價門票約50元(2–6歲含陪同者),場次制(週三至週日每日4場,09:00–16:20);園區9:00–17:00,週一二公休",
  "tn-taijiang-visitor-center": "館區免門票,開放09:00-17:00(每週一及除夕休館);周邊設有免費停車場",
  "tn-sicao-green-tunnel": "搭船全票200元、兒童/優待票100元(線上約90元)、6歲以下黑琵票30元;夏季約8:30-17:00,固定10:00與14:30發船、滿員加開;天候不佳可能停航",
  "tn-nmth": "全票100元、優待票50元,未滿6歲兒童免票;兒童廳採分場次(上午09:30-12:00、下午14:00-16:30、中間清場);停車小客車50元/次、機車免費",
  "tn-yantian-eco-village": "鹽田生態文化村園區免費開放;安順吉鹽故事館開放09:00-16:30、週一休館,提供導覽解說,台江鯨豚館/鳥類生態館僅假日開放",
  "tn-luermen-shengmu-temple": "廟宇免費參觀,開放05:00-21:00;二樓宮廷古風攝影棚漢服體驗100元/20分鐘、全區300元/60分鐘;設有停車場",
  "tn-nanke-archaeology": "全票80元、團體票60元、優待票50元;65歲以上、未滿6歲、身障及陪同者免費。兒童廳/4D海洋劇場假日建議先線上預約,平日現場報到",
  "tn-tree-valley-science": "2025/1/15起票價調整:全票80元、優惠票/團體票60元、未滿6歲免費。可搭配隔壁樹谷農場一起玩",
  "tn-shanhua-beer": "免門票開放參觀、附免費停車場;推廣中心週一至週日09:00-18:00、廠區週一至週五09:00-16:00。深度導覽需另預約",
  "tn-tree-valley-farm": "各來源門票資訊不一致(60元/80元),購票多附贈一杯紅蘿蔔供餵動物;騎小馬每次100元自費。週一公休、週二至週五10:00-16:00、週末10:00-17:00",
  "tn-shanshang-waterworks": "博物館區全票100元、半票50元(台南市民/學生/65歲以上)、未滿6歲及山上區市民等免費;淨水池區全區免費。每日09:30-17:30(16:30停止售票),週三休園",
  "tn-wanpi-world": "2026票價:全票平日499、假日550元;學童平日380/假日430元;停車汽車80元、機車免費;綠洲水樂園為夏季限定(約5/30–10/31週末及連假10:00–16:00開放),室內守護者星際訓練館可作雨天/避暑備案",
  "tn-jianshanpi": "全票150、團體120、65歲以上75、兒童(110cm以上)100元,3歲以下免費;三合一套票(含遊船/遊園車)特價約250元;遊園小火車每人50元、遊湖畫舫每人100元含解說",
  "tn-nanyuan-farm": "全票350、敬老兒童票(4–12歲兒童及65歲以上)300、未滿4歲嬰幼兒免費;停車一輛50元;開放08:00–17:00",
  "tn-zoumalai-farm": "3歲以下免費;幼童(3–6歲)及博愛票120元/人;全票金額搜尋未明確待確認;停車轎車50、大客車100、機車20;戲水世界冬季(11月–隔年3月)不開放;平日09:00–17:00、假日08:00–17:00",
  "tn-cowhome": "入園門票80元(可折抵30元園內消費),90公分以下兒童免費;停車免費;08:00–17:00,週三公休;餵動物飼料每份約30元;火車餐廳供鮮奶鍋/火車便當;搭乘台糖五分車一度維修停駛,需行前確認復駛狀況",
  "tn-cigu-saltmountain": "入園免費;汽車清潔費100元/次;遊園小火車60元/人、腳踏天鵝船100元/台,雪鹽祭期間活動裝置另計",
  "tn-jingzaijiao-saltfield": "免門票、免費參觀;傳統曬鹽/挑鹽/收鹽體驗現場即可參加(免費或低價);設專用停車場,假日易滿;遊客中心09:00-17:30",
  "tn-beimen-crystalchurch": "婚紗美地/北門遊客中心免費、免費停車;水晶教堂主建築 2025 起圍籬施工(官方頁原標 2026/1/31 完工,截至 2026-07-19 查無獨立來源確認已完工開放),內部/近拍開放狀態請現場再確認",
  "tn-cigu-visitorcenter": "免門票、免費參觀;室內生態展示館有冷氣;設免費停車場;小火車/DIY/霜淇淋等體驗另計;開放09:00-17:30,週一及除夕休館"
};
const FREE = new Set(["luodong-sports-park","yilan-sports-park","longtan-lake-scenic-area","wuyuan-water-fire-park","wooderful-life-luodong","hsus-legend-vinegar-factory","jimmy-square","luodong-cultural-working-house","meihua-lake","suao-cold-spring-park","chung-hsing-cultural-park","luodong-likoyung-library","wanglongpi","daan-forest-park","juzhixiang","jiaoxi-tangweigou","paoma-historic-trail-park","yilanbing-museum","atters-cake","imit-rice","junbaobei","annong-river-park","luodong-forestry-culture-park","lanyang-creative","changpi-lake","dongyue-spring","tiansongpi-station","shilin-residence","beitou-hotspring-museum","huashan-1914","rongxing-garden","youth-park-taipei","dahu-park","tc-beitun-childrens-park","tc-qiuhonggu-park","tc-national-taichung-theater","tc-civic-park","tc-rainbow-village","tc-fengle-sculpture-park","tc-ntmofa-children","tc-caowu-greenway","tc-taichung-park","tc-4th-credit-union","tc-cultural-heritage-park","tc-nlpi-library","tc-lihpao-outlet","tc-waipu-wangyou-valley","tc-baigu-manor","tc-gaomei-wetland","tc-aofeng-gulu-park","tc-mitsui-outlet-port","tc-wuqi-fishing-port","tc-qingshui-ghost-cave","tn-linmoniang-park","tn-anping-saltoffice","tn-hele-plaza","tn-confucius-temple","tn-fire-museum","tn-barclay-park","tn-ncku-campus","tn-tainan-park","tn-taijiang-visitor-center","tn-yantian-eco-village","tn-luermen-shengmu-temple","tn-shanhua-beer","tn-cigu-saltmountain","tn-jingzaijiao-saltfield","tn-beimen-crystalchurch","tn-cigu-visitorcenter"]);
const MEAL = new Set(["shuilu-kids-cafe","lanyang-estuary-kids-restaurant","amaze-rabbit-maze-jiaoxi-bath","gitu-cafe-manor","anyo-museum","ncfta-yilan","jianiao-garden","luwu-japanese-garden","herbelle","toucheng-leisure-farm","shengyang-water-plant-farm","lanyang-creative","huashan-1914","maokong-gondola","tc-nmns-science-museum","tc-carton-king-dakeng","tc-island-aurora","tc-national-taichung-theater","tc-tongyou-forest","tc-caowu-greenway","tc-showtime-station-front","tc-lihpao-land","tc-lihpao-outlet","tc-zhongshe-flower","tc-xinshe-castle","tc-lavender-forest","tc-dongshi-forest","tc-muxinquan-farm","tc-baigu-manor","tc-gaomei-wetland","tc-mitsui-outlet-port","tc-wuqi-fishing-port","tn-art-museum-2","tn-nanke-archaeology","tn-shanhua-beer","tn-shanshang-waterworks","tn-wanpi-world","tn-jianshanpi","tn-nanyuan-farm","tn-zoumalai-farm","tn-cowhome","tn-cigu-saltmountain"]);
const COFFEE = new Set(["shuilu-kids-cafe","gitu-cafe-manor","lao-si-g-tea-coffee","amaze-rabbit-maze-jiaoxi-bath","bambi-land","luodong-cultural-working-house","meihua-lake","yi-nong-ranch","chung-hsing-cultural-park","juzhixiang","jianiao-garden","xingbao-scallion-farm","herbelle","luwu-japanese-garden","huashan-1914","maokong-gondola","tc-nmns-science-museum","tc-carton-king-dakeng","tc-island-aurora","tc-national-taichung-theater","tc-tongyou-forest","tc-caowu-greenway","tc-4th-credit-union","tc-cultural-heritage-park","tc-showtime-station-front","tc-lihpao-land","tc-lihpao-outlet","tc-xinshe-castle","tc-lavender-forest","tc-muxinquan-farm","tc-baigu-manor","tc-gaomei-wetland","tc-mitsui-outlet-port","tn-art-museum-2","tn-nanke-archaeology","tn-shanhua-beer","tn-shanshang-waterworks"]);

const slim = venues.map(v => ({
  id: v.id, name: v.name, type: v.type,
  zone: v.zone || '宜蘭',
  address: v.location.address,
  drive: v.location.drive_min,
  shade: v.shade_score.score,
  shade_basis: v.shade_score.basis,
  noise: v.noise_tolerance.score,
  noise_basis: v.noise_tolerance.basis,
  ride: { ok: v.ride_ok.ok, note: v.ride_ok.note },
  fac: v.facilities,
  fee: FEE_SHORT[v.id] || '待確認',
  fee_full: FEE_FULL[v.id] || '',
  evidence: v.evidence,
  games: v.games || [],
  weather_fit: v.weather_fit,
  age_fit: Object.fromEntries(Object.entries(v.age_fit).map(([b, a]) => [b, { score: a.score, reason: a.reason }])),
  rain_backup_id: v.rain_backup_id,
  family_log: v.family_log,
  last_verified: v.last_verified,
  status: v.status,
  flags: { free: FREE.has(v.id), meal: MEAL.has(v.id), coffee: COFFEE.has(v.id) },
}));

const family = { children: fam.children.map(c => ({ nickname: c.nickname, birth: String(c.birth).slice(0, 7) })) };

// 大人模式資料(data/places-adult.json;檔案不存在時為空陣列)
let adultRaw = [];
try { adultRaw = JSON.parse(fs.readFileSync(path.join(R, 'data/places-adult.json'), 'utf8')); } catch (e) { adultRaw = []; }
const places = adultRaw.filter(p => p && p.id).map(p => ({
  id: p.id, name: p.name, type: p.type,
  zone: p.zone || '台北', district: p.district || '',
  address: (p.location && p.location.address) || '待確認',
  price_level: (p.price_band && p.price_band.level) || null,
  price_per: (p.price_band && p.price_band.per_person) || '待確認',
  price_basis: (p.price_band && p.price_band.basis) || '',
  meal_type: p.meal_type || [],
  scene_fit: p.scene_fit || {},
  vibe: p.vibe || [],
  open_late: p.open_late || {},
  reservation: p.reservation || {},
  work_ok: p.work_ok || {},
  signature: p.signature || '',
  evidence: p.evidence || [],
  last_verified: p.last_verified || '',
  status: p.status || 'active',
}));

let html = fs.readFileSync(path.join(R, 'template.html'), 'utf8');
html = html.replace('__VENUES__', () => JSON.stringify(slim))
  .replace('__PLACES__', () => JSON.stringify(places))
  .replace('__FAMILY__', () => JSON.stringify(family))
  .replaceAll('__BUILD_DATE__', TODAY)
  .replace('__N__', String(slim.length))
  .replaceAll('__NA__', String(places.length));

fs.mkdirSync(DIST, { recursive: true });
fs.writeFileSync(path.join(DIST, 'index.html'), html);
for (const f of ['time.html', 'icon-192.png', 'icon-512.png']) fs.copyFileSync(path.join(R, f), path.join(DIST, f));

fs.writeFileSync(path.join(DIST, 'manifest.json'), JSON.stringify({
  name: '林家出遊手冊', short_name: '出遊手冊',
  start_url: './index.html', scope: './', display: 'standalone',
  background_color: '#F7F3EC', theme_color: '#2E7D74',
  icons: [
    { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: 'icon-512.png', sizes: '512x512', type: 'image/png' },
  ],
}, null, 2));

const CACHE = 'lin-family-' + Date.now();
fs.writeFileSync(path.join(DIST, 'sw.js'), [
  'const C = ' + JSON.stringify(CACHE) + ';',
  "const ASSETS = ['./', './index.html', './time.html', './manifest.json', './icon-192.png', './icon-512.png'];",
  "self.addEventListener('install', e => { e.waitUntil(caches.open(C).then(c => c.addAll(ASSETS)).then(() => self.skipWaiting())); });",
  "self.addEventListener('activate', e => { e.waitUntil(caches.keys().then(ks => Promise.all(ks.filter(k => k !== C).map(k => caches.delete(k)))).then(() => self.clients.claim())); });",
  "self.addEventListener('fetch', e => {",
  "  if (e.request.method !== 'GET') return;",
  "  e.respondWith(caches.match(e.request).then(cached => {",
  "    const fresh = fetch(e.request).then(r => { if (r && r.ok && new URL(e.request.url).origin === location.origin) { const cl = r.clone(); caches.open(C).then(x => x.put(e.request, cl)); } return r; }).catch(() => cached);",
  "    return cached || fresh;",
  "  }));",
  "});",
].join('\n'));

console.log('dist/ 產出完成:index.html(' + (html.length / 1024).toFixed(1) + 'KB,親子 ' + slim.length + ' 筆 / 大人 ' + places.length + ' 家)+ time.html + manifest + sw + icons');
